### ISSUE TITLE
isExistedFile checking iOS app bundle

### ISSUE THREAD

**Issue by chenchaoyi** [macacajs/webdriver-server#32]
https://github.com/macacajs/webdriver-server/blob/master/lib/common/helper.js#L183 seems causing problem when checking iOS app bundle, which is a dir in the file system.

**Comment by zenzhu** [comment]
Thanks for reporting. #33

**Comment by chenchaoyi** [comment]
hum... 
`if (!_.isExistedFile(appPath) || !_.isExistedDir(appPath))`  ->

`if (!_.isExistedFile(appPath) && !_.isExistedDir(appPath))` 

**:)**

**Comment by zenzhu** [comment]
oops...#34...fixed.

**Comment by chenchaoyi** [comment]
👍
